### ISSUE TITLE
Deployment pipeline

### ISSUE THREAD

**Issue by olivier5741** [wecitizens/regional-gps-app#11]
@danielsum, can you please set up a deployment pipeline ?

From windows, I don't know how to deploy ... I can play with travis but I have no way to fix stuff if I break things while implementing the pipeline.

https://docs.travis-ci.com/user/deployment/codedeploy/ (don't forget to hide sensible info)

**Comment by danielsum** [comment]
@olivier5741  => ok this should be solved using own repository url to deploy (info in mail if needed)
