### ISSUE TITLE
Add Screen : determination of the electoral districts of the user

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#12]
@danielsum 
The easiest way for the developer is to ask the user:
Choose your electoral district:
     For the European elections: ...  (see menus in Q41-specs > § 9.2.3.)
     For the Federal elections
     For te Regional elections

For the user, a better alternative would be the following:
The system asks:
Postal code :   ….
Linguistic choice:     NL/FR/DE

Based on these two answers, the system then determines the three Elections applicable to the user, and the corresponding districts.
The applicable rules are explained in : 
http://www.wecitizens.be/docs-fr/B-Reglementation-circonscriptions-electorales.pdf  
in combination with :  http://www.wecitizens.be/docs-fr/B-Districts.xlsx

**Comment by danielsum** [comment]
Voir design : https://docs.google.com/presentation/d/1rnfCHWZTBiGpcGZ4jaarROc1N-9tT_6HMeEPqq2t1X4/edit#slide=id.g4baef558c4_0_32

**Comment by JPPinon** [comment]
On a décidé, que dans un premier temps on développe le GPS selon la formule la plus facile pour le développeur. Je crois qu'il vaut mieux faire défiler trois écrans pour pour les trois niveaux de pouvoir:

**Choisissez votre circonscription pour les élections européennes:**
Collège   électoral français (Élections européennes)
Collège   électoral flamand (Élections européennes)
Collège   électoral germanophone (Élections européennes)

**Choisissez votre circonscription pour les élections fédérales:**
Province   du Brabant wallon
Province du   Hainaut
Province du   Liège
Province du   Luxembourg
Province du   Namur
Bruxelles
Province du   Anvers
Province du   Limbourg
Province de   Flandre occidentale
Province de   Flandre orientale
Province du   Brabant flamand

**Choisissez votre circonscription pour les élections régionales:**
Bruxelles:
      groupe francophone
      groupe néerlandophone
Flandre:
   Province du Anvers
   Province du Limbourg
   Province de Flandre occidentale
   Province de Flandre orientale
   Province du Brabant flamand
Wallonie:
   Province du Luxembourg
   circonscription de Mons
   circonscription de Soignies - La Louvière
   circonscription de Tournai – Ath - Mouscron
   circonscription de Charleroi-Thuin
   Province du Brabant wallon
   circonscription de Liège
   circonscription de Huy - Waremme  circonscription de Verviers
   circonscription de Namur
   circonscription de Dinant - Philippeville

**Comment by danielsum** [comment]
@JPPinon => je ne trouve pas cette liaison au niveau de la DB PROD.... => du coups comment je fais ? ^'

**Comment by JPPinon** [comment]
Supposons que l’utilisateur choisisse l’élection Région wallonne 2019.
Dans la table poldir.elections, il s’agit du n° 24 (ID) avec ‘elected_authority’=BERWA
Les districts qui doivent figurer au menu sont tous ceux de la table poldir.electoral_district pour lesquels  ‘elected_authority’=BERWA
Donc l’utilisateur devra choisir entre : WA, WD, … WF
Les intitulés de ces circonscriptions se trouvent dans la même table : poldir.electoral_district

Est-ce que cela répond à ta question?

**Comment by danielsum** [comment]
Non pas vraiment => je ne trouve pas la correspondance dans la DB actuel => dans electoral_district j'ai ça...

https://www.evernote.com/l/AHfw4quLq_9AAon0QemjX8g9Wt2xkhv-ZDI

=> pas possible pour moi de produit une liste avec les infos données plus haut du coups...

**Comment by JPPinon** [comment]
attention tu confond election_district (une table périmée; ou qui n'aurait jamais dû exister) et la table electoral_districts
