### ISSUE TITLE
Construction of a combined questionnaire for three elections

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#14]
@danielsum 
Pour le 26/5/2019, il y aura 5 GPS électoraux : Europe, Belgique fédérale, 3 Régions.
Chaque GPS devrait compter autour de 20 questions.
On a pris le parti de soumettre aux utilisateurs un seul questionnaire « combiné », mélangeant les trois GPS qui lui sont applicables.
Le maximum théorique serait de 60 questions, mais nous comptons sur de nombreuses questions polyvalentes (càd valables pour plus d’un GPS électoral). De fait, on souhaite plafonner le questionnaire « combiné » à 40 questions.
Le GPS devra soumettre un questionnaire qui sera la fusion de trois questionnaires, en respectant l'ordre de priorité de présentation des questions.

**Comment by danielsum** [comment]
Pour rappel => me fournir donc les 5 GPS éléctoraux même non remplis pour que je puisse dynamiser cette partie.

Merci !

**Comment by JPPinon** [comment]
@danielsum Gaël me dit qu'il t'a transmis les données concernant les 5 GPS électoraux. Est-ce OK?

**Comment by danielsum** [comment]
@JPPinon => merci de mettre les bons intitulés pour les 5 GPS : http://testpoldir.wecitizens.be/fr/questionnaire

**Comment by JPPinon** [comment]
@danielsum Comme précisé ailleurs, l'intitulé d'une élection est la concaténation de :
- le texte dans la table [poldir.elected_authority] qui correspond à l'abbr correspondante [poldir.Election.elected_authority] et à la langue
- l'année: [poldir.election.year]

**Comment by JPPinon** [comment]
Jean-Michel me demande:
Est-ce qu'une limite  doit être effectivement  prévue dans le query sur la DB ?
Réponse: non.
On a résolu le problème de la longueur en indiquant à l'utilisateur qu'il peut interrompre l'interrogatoire quand il veut.
