### ISSUE TITLE
Vote recommendation tool

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#20]
In 2019 we have the first clients who use WeCitizens’ services to establish a ranking of candidates in each district.
We use the same display of results as for the Electoral GPS.

For each client we have to create separate “elections”. Concretely, in table [Poldir/Election] we have following IDs:
21 = Electoral GPS - EU election 	26-05-2019
22 = Electoral GPS – Federal election	26-05-2019
23 = Electoral GPS – Flemish Region 	26-05-2019
24 = Electoral GPS – Walloon Region 	26-05-2019
25 = Electoral GPS – Brussels Region 	26-05-2019
26 = c’axent - EU election 	27-04-2019
27 = c’axent - Federal election 	27-04-2019
28 = c’axent – Flemish Region 	27-04-2019
29 = c’axent – Brussels Region 	27-04-2019

We use the date of the election, to distinguish between an election-for-the-GPS and an election-for-a-client.
In the case of c’axent, they do not deal with Walloon Region.
We provide their answers on all their questions.
We need page where a user just needs to:
•	choose Between Flemish and Brussels region
this can be a page similar to the one of the GPS, but with two differences:
o	Title: Ranking of candidates/parties according to the values of c’axent
o	No possibility to choose Walloon Region
It is the welcome page for the people of c’axent: c’axent will spread the URL to this page
•	after that, choose your district for each election (European, Federal, Region)
same page as for the GPS

There is no questionnaire for the “user”. (All questions are answered by a unique answerer).
So, once the user has chosen the districts, he goes right to the result pages, applicable to his districts.

**Comment by danielsum** [comment]
@jm768van => techniquement faisable ? 

On peut faire un fork de l'app et de l'api si nécessaire pour ça

**Comment by jm768van** [comment]
faut-il, ou, peut-on laisser la possibilité de voir les réponses aux questions ? 
Peut-on laisser la barre:   Cisconscription - Questions - Stats -Results ?
