### ISSUE TITLE
landing page 

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#24]
Les gens qui arrivent sur gps.wecitizens.be trouvent le GPS communal.
Il faut d'urgence remplacer par une page disant:
"Le GPS électoral pour les élections législatives du 26 mai 2019 sera mis en ligne très prochainement."
"De KiesWijzer voor de parlementsverkiezingen van 26 mei 2019 zal zeer binnenkort beschikbaar zijn."
"The Electoral GPS for the legislative elections of 26 May 2019 will be available soon."

**Comment by danielsum** [comment]
@JPPinon => c'est fait
