### ISSUE TITLE
Photos de candidts apparaissent à la place du logo du parti

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#28]
Dans les résultats du GPS, onglet partis, je trouve la photo d'une candidate (Sarah Tshikuna Mbuyi):
![image](https://user-images.githubusercontent.com/43548775/57966390-8a3bd680-7951-11e9-93fb-0f10a6ed9884.png)

au lieu du logo du parti: 
![image](https://user-images.githubusercontent.com/43548775/57966395-96279880-7951-11e9-829f-2feae5c9d948.png)

En fait il y a souvent des logos de partis remplacés par des photos de candidats

**Comment by danielsum** [comment]
@jm768van => tu as une idée pourquoi ? Est-ce que ça vient du serveur ou à cause d'une mauvaise query dans l'api ?

**Comment by jm768van** [comment]
je pencherais pour un bug dans le query de l'API.

**Comment by JPPinon** [comment]
Le problème subsiste. Mieux vaut ne pas afficher de logo dans la liste des partis.

**Comment by jm768van** [comment]
Image provisoirement supprimée de l'affichage pur les partis.
