### ISSUE TITLE
format des photos, dans l'affichage des résultats

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#29]
Le score (%) est à peine lisible. 
Essayer de réduire l'espace blanc: tendre à ce que la hauteur de la photo ne soit pas beaucoup plus que la hauteur du texte à côté.

Pourquoi le photos ont des formats différents?

![image](https://user-images.githubusercontent.com/43548775/57966517-36ca8800-7953-11e9-93ee-5a809b87fa01.png)

**Comment by danielsum** [comment]
@JPPinon les photos viennent du Directory et ne sont pas tous dans un format carré ce qui fausse le calcul de l'image..

On avait exactement le même problème avant => je préoconise de forcer la taille à la hauteur maximal de la ligne.

=> par contre il faudrait forcer le format carré dans le directory
