### ISSUE TITLE
Matching methodology and GPS mismatch : question skipping

### ISSUE THREAD

**Issue by olivier5741** [wecitizens/regional-gps-app#3]
From @JPPinon 

J'ai testé demo et le matching a l'air de fonctionner. Sauf un point qui n'est pas conforme à la méthodologie publiée ( http://www.wecitizens.be/docs-en/Q22-Matching_methodology.pdf ). Au bas du premier tableau on y dit:
(1) When a voter clicks on “I give no opinion”, it has the same effect as “no answer” (=
skipping that question).

**Comment by JPPinon** [comment]
I confirm: next version should abide by the rule that : When a voter clicks on “I give no opinion”, it has the same effect as “no answer” (=skipping that question).
The effect of answering "I give no opinion", must no be the same for users as for politicians.
When a user has no opinion on a particular question, it would be counter-productive to still use that question in the matching process.

**Comment by danielsum** [comment]
@olivier5741  => if you have some times you can maybe explain what I need to do on this task (if not good trip in Australia ! :-D)

**Comment by JPPinon** [comment]
@danielsum Cette question ne devrait pas être "on hold".
On développera en première instance le logiciel pour ne travailler qu’avec les candidats ayant répondu à toutes les questions de leur GPS électoral. Dans ce cas, il n'y a pas de pénalité à appliquer. (La formule de pénalité mentionnée dans la notice méthodologique, donne zéro pénalité: http://www.wecitizens.be/docs-en/Q22-Matching_methodology.pdf )
L’extension aux candidats n’ayant répondu que partiellement, sera offerte comme option aux utilisateurs, pourvu que le logiciel soit opérationnel à cet effet. L’utilisateur pourrait alors basculer entre un classement avec ou sans les candidats ayant répondu partiellement.
