### ISSUE TITLE
Disposition des listes de résultats

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#30]
Actuellement, il faut scroller tout en bas de la liste de la Région, pour trouver la liste fédérale, etc
C'est très peu ergonomique. 
Ne peut-on pas avoir trois onglets tout en haut, pour les trois élections?

**Comment by danielsum** [comment]
@JPPinon => j'ai regroupé les 3 éléctions en tabs => en cliquant sur le titre ça déplie/replie les éléctions (bon compris entre voir une éléctions ou toutes les élections)

Quand on imprime => je dois déplier toutes les listes par contre pas possible d'avoir les 3 elections + 3 listes dépliés => par defaut l'impression va imprimer les partis et si l'utilisateur choisi une autre tab => la tab active.

**Comment by JPPinon** [comment]
S'il faut choisir un onglet par défaut, je préfère que ce soit les candidats effectifs. Mais je préfère qu'on imprime tout.
Chez moi, la barre du score ne s'imprime pas. Ce n'est pas un problème, et cela me donne l'idée suivante.
Ne pourrait-on pas imprimer sans les photos, une ligne par candidat avec le nom complet, parti, place sur la liste et score? Cela éviterait une inflation de pages imprimées.

COULD On pourrait éventuellement plafonner le nombre de candidats qu'on imprime pour une même élection, p.ex. à 20.

**Comment by JPPinon** [comment]
Actuellement cela imprime les onglet ouverts sur l'écran. Il faudrait imprimer les neuf onglets.
