### ISSUE TITLE
Erreur de calcul du matching

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#31]
Je prend le cas de "Test Femme" ID 19691.
Elle est candidate Ecolo suppléante à Nivelles pour les élections régionales wallonne.
Ci-joint le tableau avec les scenarii.
[Q41-190419-opinion_answers-for testing.xlsx](https://github.com/wecitizens/regional-gps-app/files/3193851/Q41-190419-opinion_answers-for.testing.xlsx)

Dans le scenario A, l'utilisateur répond "tout à fait d'accord" aux 5 premières questions, et ne répond à aucune autre question. 
Le GPS lui donne un score de 36% 
![image](https://user-images.githubusercontent.com/43548775/57967086-0555ba80-795b-11e9-8baf-07fd30d84645.png)

D'après mon calcul, "Test-Femme" devrait avoir un score de 28%
comme elle n'a pas répondu aux questions 136 et 140, son score doit être calculé sur les trois première questions. La formule donne:
=100*(1-SQRT(POWER(75;2)+POWER(100;2)+POWER(0;2))/SQRT(10000*3)) = 27,83

**Comment by jm768van** [comment]
tu avais fait un test similaire pour les communales ?     
( pour éventuellement identifier si c'est un problème lié aux données livrées  à l'algo ou un problème dans l'algo)

**Comment by JPPinon** [comment]
Autre cas "180920 Test" ID 12098, est candidat Groen à Bruxelles pour les régionales.
Dans le scénario B, il obtient un score de 55% dans le GPS:
![image](https://user-images.githubusercontent.com/43548775/57972330-17564e00-7999-11e9-9e2b-807e34d646f2.png)

D'après moi (même sans calcul) il devrait avoir 25%. En effet, il n'y a qu'une seule question qui peut servir pour établir le score, la première du questionnaire, càd la n° 120. Je ne comprends donc pas comment on peut arriver à 55%. 

Pour rappel, lorsque l'utilisateur "skip" la question, ou qu'il y répond "je ne me prononce pas", la question est écartée pour le calcul du score.

**Comment by JPPinon** [comment]
Test simple: en tant qu'utilisateur je réponds uniquement à la première question (la n°120). Réponse "tout à fait d'accord" = 1
Candidate 180920 Test a répondu "plutôt pas d'accord" = 4
Donc le score du candidat doit être de 25%
Or je trouve : 75% !

**Comment by JPPinon** [comment]
Derniers test OK !!!
