### ISSUE TITLE
compléter l'écran des résultats

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#32]
En bas de l'écran des résultats, il n'y a pas les mentions prévues dans le wireframe: 
 * possibilité d'imprimer les résultats (très utile pour prendre avec soi, en route pour la cabine de vote). dans issue n°13 @danielsum  disait que c'était arrangé.     SHOULD
 * faire un don   SHOULD
 * (s'envoyer un email avec un lien vers le résultat)   COULD
 * (revenir au questionnaire)                                       COULD

**Comment by danielsum** [comment]
Fais pour les Shoulds => pour les Could je dois demander à JM si techniquement possible (je lui avait parlé du besoin mais je pense qu'il a pas compris)
