### ISSUE TITLE
petite erreur de multilinguisme

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#33]
Voici une phrase qui n'est pas traduite, et ne figure pas dans le language file:
![image](https://user-images.githubusercontent.com/43548775/58074823-7341f200-7ba6-11e9-9db8-213caeb32d3e.png)

**Comment by jm768van** [comment]
la traduction devrait se trouver sous Dropbox?

**Comment by danielsum** [comment]
@jm768van => ça se trouve ici => j'exporte la ligne dans le spreadsheet puis je lance /bin/sync-translations.js pour mettre à jour les textes

**Comment by JPPinon** [comment]
non, sur Google Drive: https://docs.google.com/spreadsheets/d/1cCEj3O8wowwyyp2KXlTRtSxN0T2UBivDvyKRoVk9aS4/edit?usp=sharing

**Comment by danielsum** [comment]
Done
