### ISSUE TITLE
End user mail to candidate

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/regional-gps-app#7]
Dans l'écran 3, sous la liste de candidats, y aurait-il moyen d'ajouter un truc permettant au citoyen d'envoyer un message à un candidat (dont il connaît l'adresse email) ne figurant pas dans la liste ?

**Comment by danielsum** [comment]
@JPPinon => est-ce tjs d'actualité ? Doit-t-on envoyer le mail au nom de We Citizens pour intercepter le mail du candidat ?

**Comment by JPPinon** [comment]
@danielsum 
Il s'agit d'un [could have]. ci-joint le texte actualisé du "reminder".
[Q41-190305-reminder.docx](https://github.com/wecitizens/regional-gps-app/files/2931110/Q41-190305-reminder.docx)

La procédure idéale pour l'envoi d'un reminder est décrite dans Dropbox WWN-IT > Q41-specs > §6.5.2.
La meilleure solution serait que l'email soit envoyé par la boîte email du citoyen, avec copie à info@wecitizens.be
